<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="amr">

    <!-- Add namespace -->

    <xacro:arg name="namespace" default=""/>

    <!-- ................................ material .................................. -->

    <material name="white">
        <color rgba="1 1 1 1"/>
    </material>

    <material name="grey">
        <color rgba="0.5 0.5 0.5 1"/>
    </material>

    <material name="black">
        <color rgba="0.1 0.1 0.1 1"/>
    </material>

    <material name="silver">
        <color rgba="0.79 0.82 0.93 1" />
    </material>

    <!-- ................................ inertial with origin .................................. -->

    <xacro:macro name="sphere_inertial" params="radius mass *origin">
        <inertial>
        <mass value="${mass}" />
        <xacro:insert_block name="origin" />
        <inertia ixx="${0.4 * mass * radius * radius}" ixy="0.0" ixz="0.0"
            iyy="${0.4 * mass * radius * radius}" iyz="0.0"
            izz="${0.4 * mass * radius * radius}" />
        </inertial>
    </xacro:macro>

    <xacro:macro name="cylinder_inertial" params="radius length mass *origin">
        <inertial>
        <mass value="${mass}" />
        <xacro:insert_block name="origin" />
        <inertia ixx="${0.0833333 * mass * (3 * radius * radius + length * length)}" ixy="0.0" ixz="0.0"
            iyy="${0.0833333 * mass * (3 * radius * radius + length * length)}" iyz="0.0"
            izz="${0.5 * mass * radius * radius}" />
        </inertial>
    </xacro:macro>

    <xacro:macro name="box_inertial" params="x y z mass *origin">
        <inertial>
        <mass value="${mass}" />
        <xacro:insert_block name="origin" />
        <inertia ixx="${0.0833333 * mass * (y*y + z*z)}" ixy="0.0" ixz="0.0"
            iyy="${0.0833333 * mass * (x*x + z*z)}" iyz="0.0"
            izz="${0.0833333 * mass * (x*x + y*y)}" />
        </inertial>
    </xacro:macro>

    <!-- 缩放因子 0.65 0.7 测试通过 -->
    <xacro:property name="scale" value="0.75" /> 
    <xacro:property name="mass_scale" value="${scale * scale * scale}" />
    
    <xacro:property name="deg_to_rad" value="0.017453293" />

    <!-- BASE 尺寸和惯性 -->
    <xacro:property name="amr_base_inertial_x" value="${-0.05 * scale}" />
    <xacro:property name="amr_base_inertial_y" value="0.0" />
    <xacro:property name="amr_base_inertial_z" value="${0.15 * scale}" />
    <xacro:property name="amr_base_inertial_x_length" value="${0.50 * scale}" />
    <xacro:property name="amr_base_inertial_y_length" value="${0.30 * scale}" />
    <xacro:property name="amr_base_inertial_z_length" value="${0.20 * scale}" />

    <xacro:property name="amr_base_mass" value="${77.0 * mass_scale}" />
    <xacro:property name="amr_act_wheel_radius" value="${0.0625 * scale}" />
    <xacro:property name="amr_act_wheel_width" value="${0.032 * scale}" />
    <xacro:property name="amr_act_wheel_mass" value="${1.0 * mass_scale}" />
    <xacro:property name="amr_act_wheel_dx" value="${0.037646 * scale}" />
    <xacro:property name="amr_act_wheel_dy" value="${0.222604 * scale}" />

    <xacro:property name="amr_caster_wheel_radius" value="${0.0625 * scale}" />
    <xacro:property name="amr_caster_wheel_width" value="${0.032 * scale}" />
    <xacro:property name="amr_caster_wheel_mass" value="${1.0 * mass_scale}" />
    <xacro:property name="amr_caster_wheel_dx" value="${-0.0382 * scale}" />
    <xacro:property name="amr_caster_wheel_dy" value="0" />
    <xacro:property name="amr_caster_wheel_dz" value="${-0.094 * scale}" />
    <xacro:property name="amr_front_caster_wheel_base_dx" value="${0.3037 * scale}" />
    <xacro:property name="amr_back_caster_wheel_base_dx"  value="${0.3078 * scale}" />
    <xacro:property name="amr_caster_wheel_base_dy" value="${0.203 * scale}" />
    <xacro:property name="amr_caster_wheel_base_dz" value="${amr_caster_wheel_radius - amr_caster_wheel_dz}" />

    <xacro:property name="laser_dx" value="${0.392 * scale}" />
    <xacro:property name="laser_dy" value="${0.2358 * scale}" />
    <xacro:property name="laser_dz" value="${0.1914 * scale}" />

    <!-- ................................ BASE LINK .................................. -->

    <link name="base_footprint"/>

    <joint name="base_joint" type="fixed">
        <parent link="base_footprint" />
        <child link="base_link" />
        <origin xyz="0 0 0" rpy="0 0 0" />
    </joint>

    <link name="base_link">
        <xacro:box_inertial mass="${amr_base_mass}" x="${amr_base_inertial_x_length}" y="${amr_base_inertial_y_length}" z="${amr_base_inertial_z_length}">
            <origin xyz="${amr_base_inertial_x + amr_act_wheel_dx} ${amr_base_inertial_y} ${amr_base_inertial_z}" rpy="0 0 0" />
        </xacro:box_inertial>
        <visual>
            <origin xyz="${amr_act_wheel_dx} 0 0" rpy="0 0 0" />
            <geometry>
                <mesh filename="file://$(find amr_description)/meshes/visual/amr_base.stl" scale="${scale} ${scale} ${scale}" />
            </geometry>
            <material name="white"/>
        </visual>
        <collision>
            <origin xyz="${amr_act_wheel_dx} 0 0" rpy="0 0 0" />
            <geometry>
                <mesh filename="file://$(find amr_description)/meshes/collision/amr_base.stl" scale="${scale} ${scale} ${scale}" />
            </geometry>
        </collision>
    </link>

    <gazebo reference="base_link">
        <material>Gazebo/White</material>
    </gazebo>

    <!-- ................................ WHEELS ..................................... -->

    <joint name="left_wheel_joint" type="continuous">
        <origin xyz="0.0 ${-amr_act_wheel_dy * -1.0} ${amr_act_wheel_radius}" rpy="0 0 0" />
        <parent link="base_link" />
        <child link="left_wheel_link" />
        <axis xyz="0 1 0" />
        <limit effort="100" velocity="20.0" />
    </joint>

    <link name="left_wheel_link">
        <xacro:cylinder_inertial mass="${amr_act_wheel_mass}" radius="${amr_act_wheel_radius}" length="${amr_act_wheel_width}">
            <origin xyz="0 0 0" rpy="${0.5 * pi} 0 0" />
        </xacro:cylinder_inertial>
        <visual>
            <origin xyz="0 0 0" rpy="${pi/2} 0 0" />
            <geometry>
                <cylinder radius="${amr_act_wheel_radius}" length="${amr_act_wheel_width}" />
            </geometry>
            <material name="black"/>
        </visual>
        <collision>
            <origin xyz="0 0 0" rpy="${pi/2} 0 0" />
            <geometry>
                <cylinder radius="${amr_act_wheel_radius}" length="${amr_act_wheel_width}" />
            </geometry>
        </collision>
    </link>
    
    <gazebo reference="left_wheel_link">
        <material>Gazebo/FlatBlack</material>
    </gazebo>

    <joint name="right_wheel_joint" type="continuous">
        <origin xyz="0.0 ${-amr_act_wheel_dy * 1.0} ${amr_act_wheel_radius}" rpy="0 0 0" />
        <parent link="base_link" />
        <child link="right_wheel_link" />
        <axis xyz="0 1 0" />
        <limit effort="100" velocity="20.0" />
    </joint>

    <link name="right_wheel_link">
        <xacro:cylinder_inertial mass="${amr_act_wheel_mass}" radius="${amr_act_wheel_radius}" length="${amr_act_wheel_width}">
            <origin xyz="0 0 0" rpy="${0.5 * pi} 0 0" />
        </xacro:cylinder_inertial>
        <visual>
            <origin xyz="0 0 0" rpy="${pi/2} 0 0" />
            <geometry>
                <cylinder radius="${amr_act_wheel_radius}" length="${amr_act_wheel_width}" />
            </geometry>
            <material name="black"/>
        </visual>
        <collision>
            <origin xyz="0 0 0" rpy="${pi/2} 0 0" />
            <geometry>
                <cylinder radius="${amr_act_wheel_radius}" length="${amr_act_wheel_width}" />
            </geometry>
        </collision>
    </link>

    <gazebo reference="right_wheel_link">
        <material>Gazebo/FlatBlack</material>
    </gazebo>

    <joint name="fl_caster_rotation_joint" type="continuous">
        <origin xyz="${amr_front_caster_wheel_base_dx + amr_act_wheel_dx} ${-amr_caster_wheel_base_dy * -1} ${amr_caster_wheel_base_dz}" rpy="0 0 0" />
        <parent link="base_link" />
        <child link="fl_caster_rotation_link" />
        <axis xyz="0 0 1" />
        <dynamics damping="0.01" friction="0.0"/>
    </joint>

    <link name="fl_caster_rotation_link">
        <inertial>
            <origin xyz="0 0 -0.042500000044" rpy="${24 * deg_to_rad} 0 ${0.5 * pi}" />
            <mass value="0.3097539019" />
            <inertia ixx="0.0005844517978" ixy="0" ixz="0" iyy="0.00052872551237" iyz="0" izz="0.00017923555074" />
        </inertial>
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <geometry>
                <mesh filename="file://$(find amr_description)/meshes/visual/caster_wheel_base.stl" scale="${scale} ${scale} ${scale}" />
            </geometry>
            <material name="silver"/>
        </visual>
        <collision>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <geometry>
                <mesh filename="file://$(find amr_description)/meshes/collision/caster_wheel_base.stl" scale="${scale} ${scale} ${scale}" />
            </geometry>
        </collision>
    </link>

    <gazebo reference="fl_caster_rotation_link">
        <material>Gazebo/Grey</material>
    </gazebo>

    <joint name="fl_caster_wheel_joint" type="continuous">
        <origin xyz="${amr_caster_wheel_dx} ${-amr_caster_wheel_dy * -1} ${amr_caster_wheel_dz}" rpy="0 0 0" />
        <parent link="fl_caster_rotation_link" />
        <child link="fl_caster_wheel_link" />
        <axis xyz="0 1 0" />
    </joint>

    <link name="fl_caster_wheel_link">
        <xacro:cylinder_inertial mass="${amr_caster_wheel_mass}" radius="${amr_caster_wheel_radius}" length="${amr_caster_wheel_width}">
            <origin xyz="0 0 0" rpy="${0.5 * pi} 0 0" />
        </xacro:cylinder_inertial>
        <visual>
            <origin xyz="0 0 0" rpy="${pi/2} 0 0" />
            <geometry>
                <cylinder radius="${amr_caster_wheel_radius}" length="${amr_caster_wheel_width}" />
            </geometry>
            <material name="black"/>
        </visual>
        <collision>
            <origin xyz="0 0 0" rpy="${pi/2} 0 0" />
            <geometry>
                <cylinder radius="${amr_caster_wheel_radius}" length="${amr_caster_wheel_width}" />
            </geometry>
        </collision>
    </link>

    <gazebo reference="fl_caster_wheel_link">
        <material>Gazebo/FlatBlack</material>
    </gazebo>

    <joint name="fr_caster_rotation_joint" type="continuous">
        <origin xyz="${amr_front_caster_wheel_base_dx + amr_act_wheel_dx} ${-amr_caster_wheel_base_dy * 1} ${amr_caster_wheel_base_dz}" rpy="0 0 0" />
        <parent link="base_link" />
        <child link="fr_caster_rotation_link" />
        <axis xyz="0 0 1" />
        <dynamics damping="0.01" friction="0.0"/>
    </joint>

    <link name="fr_caster_rotation_link">
        <inertial>
            <origin xyz="0 0 -0.042500000044" rpy="${24 * deg_to_rad} 0 ${0.5 * pi}" />
            <mass value="0.3097539019" />
            <inertia ixx="0.0005844517978" ixy="0" ixz="0" iyy="0.00052872551237" iyz="0" izz="0.00017923555074" />
        </inertial>
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <geometry>
                <mesh filename="file://$(find amr_description)/meshes/visual/caster_wheel_base.stl" scale="${scale} ${scale} ${scale}" />
            </geometry>
            <material name="silver"/>
        </visual>
        <collision>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <geometry>
                <mesh filename="file://$(find amr_description)/meshes/collision/caster_wheel_base.stl" scale="${scale} ${scale} ${scale}" />
            </geometry>
        </collision>
    </link>

    <gazebo reference="fr_caster_rotation_link">
        <material>Gazebo/Grey</material>
    </gazebo>

    <joint name="fr_caster_wheel_joint" type="continuous">
        <origin xyz="${amr_caster_wheel_dx} ${-amr_caster_wheel_dy * 1} ${amr_caster_wheel_dz}" rpy="0 0 0" />
        <parent link="fr_caster_rotation_link" />
        <child link="fr_caster_wheel_link" />
        <axis xyz="0 1 0" />
    </joint>

    <link name="fr_caster_wheel_link">
        <xacro:cylinder_inertial mass="${amr_caster_wheel_mass}" radius="${amr_caster_wheel_radius}" length="${amr_caster_wheel_width}">
            <origin xyz="0 0 0" rpy="${0.5 * pi} 0 0" />
        </xacro:cylinder_inertial>
        <visual>
            <origin xyz="0 0 0" rpy="${pi/2} 0 0" />
            <geometry>
                <cylinder radius="${amr_caster_wheel_radius}" length="${amr_caster_wheel_width}" />
            </geometry>
            <material name="black"/>
        </visual>
        <collision>
            <origin xyz="0 0 0" rpy="${pi/2} 0 0" />
            <geometry>
                <cylinder radius="${amr_caster_wheel_radius}" length="${amr_caster_wheel_width}" />
            </geometry>
        </collision>
    </link>

    <gazebo reference="fr_caster_wheel_link">
        <material>Gazebo/FlatBlack</material>
    </gazebo>

    <joint name="bl_caster_rotation_joint" type="continuous">
        <origin xyz="${-amr_back_caster_wheel_base_dx + amr_act_wheel_dx} ${-amr_caster_wheel_base_dy * -1} ${amr_caster_wheel_base_dz}" rpy="0 0 0" />
        <parent link="base_link" />
        <child link="bl_caster_rotation_link" />
        <axis xyz="0 0 1" />
        <dynamics damping="0.01" friction="0.0"/>
    </joint>

    <link name="bl_caster_rotation_link">
        <inertial>
            <origin xyz="0 0 -0.042500000044" rpy="${24 * deg_to_rad} 0 ${0.5 * pi}" />
            <mass value="0.3097539019" />
            <inertia ixx="0.0005844517978" ixy="0" ixz="0" iyy="0.00052872551237" iyz="0" izz="0.00017923555074" />
        </inertial>
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <geometry>
                <mesh filename="file://$(find amr_description)/meshes/visual/caster_wheel_base.stl" scale="${scale} ${scale} ${scale}" />
            </geometry>
            <material name="silver"/>
        </visual>
        <collision>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <geometry>
                <mesh filename="file://$(find amr_description)/meshes/collision/caster_wheel_base.stl" scale="${scale} ${scale} ${scale}" />
            </geometry>
        </collision>
    </link>

    <gazebo reference="bl_caster_rotation_link">
        <material>Gazebo/Grey</material>
    </gazebo>

    <joint name="bl_caster_wheel_joint" type="continuous">
        <origin xyz="${amr_caster_wheel_dx} ${-amr_caster_wheel_dy * -1} ${amr_caster_wheel_dz}" rpy="0 0 0" />
        <parent link="bl_caster_rotation_link" />
        <child link="bl_caster_wheel_link" />
        <axis xyz="0 1 0" />
    </joint>

    <link name="bl_caster_wheel_link">
        <xacro:cylinder_inertial mass="${amr_caster_wheel_mass}" radius="${amr_caster_wheel_radius}" length="${amr_caster_wheel_width}">
            <origin xyz="0 0 0" rpy="${0.5 * pi} 0 0" />
        </xacro:cylinder_inertial>
        <visual>
            <origin xyz="0 0 0" rpy="${pi/2} 0 0" />
            <geometry>
                <cylinder radius="${amr_caster_wheel_radius}" length="${amr_caster_wheel_width}" />
            </geometry>
            <material name="black"/>
        </visual>
        <collision>
            <origin xyz="0 0 0" rpy="${pi/2} 0 0" />
            <geometry>
                <cylinder radius="${amr_caster_wheel_radius}" length="${amr_caster_wheel_width}" />
            </geometry>
        </collision>
    </link>

    <gazebo reference="bl_caster_wheel_link">
        <material>Gazebo/FlatBlack</material>
    </gazebo>

    <joint name="br_caster_rotation_joint" type="continuous">
        <origin xyz="${-amr_back_caster_wheel_base_dx + amr_act_wheel_dx} ${-amr_caster_wheel_base_dy * 1} ${amr_caster_wheel_base_dz}" rpy="0 0 0" />
        <parent link="base_link" />
        <child link="br_caster_rotation_link" />
        <axis xyz="0 0 1" />
        <dynamics damping="0.01" friction="0.0"/>
    </joint>

    <link name="br_caster_rotation_link">
        <inertial>
            <origin xyz="0 0 -0.042500000044" rpy="${24 * deg_to_rad} 0 ${0.5 * pi}" />
            <mass value="0.3097539019" />
            <inertia ixx="0.0005844517978" ixy="0" ixz="0" iyy="0.00052872551237" iyz="0" izz="0.00017923555074" />
        </inertial>
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <geometry>
                <mesh filename="file://$(find amr_description)/meshes/visual/caster_wheel_base.stl" scale="${scale} ${scale} ${scale}" />
            </geometry>
            <material name="silver"/>
        </visual>
        <collision>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <geometry>
                <mesh filename="file://$(find amr_description)/meshes/collision/caster_wheel_base.stl" scale="${scale} ${scale} ${scale}" />
            </geometry>
        </collision>
    </link>

    <gazebo reference="br_caster_rotation_link">
        <material>Gazebo/Grey</material>
    </gazebo>

    <joint name="br_caster_wheel_joint" type="continuous">
        <origin xyz="${amr_caster_wheel_dx} ${-amr_caster_wheel_dy * 1} ${amr_caster_wheel_dz}" rpy="0 0 0" />
        <parent link="br_caster_rotation_link" />
        <child link="br_caster_wheel_link" />
        <axis xyz="0 1 0" />
    </joint>

    <link name="br_caster_wheel_link">
        <xacro:cylinder_inertial mass="${amr_caster_wheel_mass}" radius="${amr_caster_wheel_radius}" length="${amr_caster_wheel_width}">
            <origin xyz="0 0 0" rpy="${0.5 * pi} 0 0" />
        </xacro:cylinder_inertial>
        <visual>
            <origin xyz="0 0 0" rpy="${pi/2} 0 0" />
            <geometry>
                <cylinder radius="${amr_caster_wheel_radius}" length="${amr_caster_wheel_width}" />
            </geometry>
            <material name="black"/>
        </visual>
        <collision>
            <origin xyz="0 0 0" rpy="${pi/2} 0 0" />
            <geometry>
                <cylinder radius="${amr_caster_wheel_radius}" length="${amr_caster_wheel_width}" />
            </geometry>
        </collision>
    </link>

    <gazebo reference="br_caster_wheel_link">
        <material>Gazebo/FlatBlack</material>
    </gazebo>

    <!-- ............................. 2D LIDAR ........................................ -->
    
    <xacro:property name="laser_x" value="0.156" />
    <xacro:property name="laser_y" value="0.155" />
    <xacro:property name="laser_z" value="0.185" />
    <xacro:property name="laser_mass" value="1.2" />
    
    <!-- Center lidar -->
    <joint name="base_link_to_center_laser_joint" type="fixed">
        <parent link="base_link" />
        <child link="center_lidar" />
        <origin xyz="0 0 0.4" rpy="0.0 0.0 0.0" />
    </joint>

    <link name="center_lidar">
        <visual>
            <origin xyz="0.0 0.0 0.0" rpy="0 0 0" />
            <geometry>
                <cylinder radius="0.001" length="0.001"/>
            </geometry>
            <material name="black"/>
        </visual>
        <collision>
            <origin xyz="0.0 0.0 0.0" rpy="0 0 0" />
            <geometry>
                <cylinder radius="0.001" length="0.001"/>
            </geometry>
        </collision>
        <xacro:box_inertial x="${laser_x}" y="${laser_y}" z="${laser_z}" mass="${laser_mass}">
            <origin xyz="0 0 0" />
        </xacro:box_inertial>
    </link>

    <gazebo reference="center_lidar">
        <gravity>true</gravity>
        <sensor type="ray" name="sick_laser">
            <always_on>true</always_on>
            <pose>0 0 0 0 0 0</pose>
            <visualize>false</visualize>
            <update_rate>25.0</update_rate>
            <ray>
                <scan>
                    <horizontal>
                    <samples>720</samples>
                    <resolution>1.000000</resolution>
                    <min_angle>0.000000</min_angle>
                    <max_angle>6.280000</max_angle>
                    </horizontal>
                </scan>
                <range>
                    <min>0.1</min>
                    <max>50.0</max>
                    <resolution>0.01</resolution>
                </range>
                <noise>
                    <type>gaussian</type>
                    <mean>0.0</mean>
                    <stddev>0.01</stddev>
                </noise>
            </ray>
            <plugin name="amr_laser" filename="libgazebo_ros_ray_sensor.so">
                <ros>
                    <namespace>$(arg robot_namespace)</namespace>
                    <remapping>~/out:=scan</remapping>
                </ros>
                <output_type>sensor_msgs/LaserScan</output_type>
                <frame_name>center_lidar</frame_name>
            </plugin>
        </sensor>
    </gazebo>

    <!-- .....................MULTI WHEEL DIFF DRIVE ................................... -->

    <gazebo>
        <plugin name="diff_drive" filename="libgazebo_ros_diff_drive.so">
            <ros>
                <namespace>$(arg robot_namespace)</namespace>
                <remapping>cmd_vel:=cmd_vel</remapping>
                <remapping>odom:=odom</remapping>
            </ros>
            <legacy_mode>false</legacy_mode>
            <update_rate>50.0</update_rate>
            <left_joint>left_wheel_joint</left_joint>
            <right_joint>right_wheel_joint</right_joint>
            <wheel_separation>${2 * amr_act_wheel_dy}</wheel_separation>
            <wheel_diameter>${2 * amr_act_wheel_radius}</wheel_diameter>
            <robot_base_frame>base_footprint</robot_base_frame>
            <max_wheel_torque>2000</max_wheel_torque>
            <max_wheel_acceleration>5.0</max_wheel_acceleration>
            <command_topic>cmd_vel</command_topic>
            <odometry_topic>odom</odometry_topic>
            <odometry_frame>odom</odometry_frame>
            <publish_odom>true</publish_odom>
            <publish_odom_tf>true</publish_odom_tf>
            <publish_wheel_tf>false</publish_wheel_tf>
            <!-- Odometry source, 0 for ENCODER, 1 for WORLD, defaults to WORLD -->
            <odometry_source>0</odometry_source>
        </plugin>
    </gazebo>

    <!--............................... Ground truth PLUGIN .............................-->

    <gazebo>
        <plugin name="p3d_base_controller" filename="libgazebo_ros_p3d.so">
            <ros>
                <namespace>$(arg robot_namespace)</namespace>
                <remapping>odom:=p3d_ground_truth</remapping>
            </ros>
            <always_on>true</always_on>
            <update_rate>50.0</update_rate>
            <body_name>base_footprint</body_name>
            <gaussian_noise>0.00</gaussian_noise>
            <frame_name>map</frame_name>
        </plugin>
    </gazebo>

</robot>
